# Generated by Django 3.2.3 on 2022-02-16 11:14

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcels',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('areah', models.FloatField(default=0, verbose_name='Area(Ha)')),
                ('perm', models.FloatField(default=0, verbose_name='Perimeter')),
                ('plotno', models.BigIntegerField(unique=True, verbose_name='Plot NO')),
                ('lrnumber', models.CharField(max_length=80, unique=True, verbose_name='LRNumber')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Geometry')),
            ],
            options={
                'verbose_name_plural': 'parcels',
                'db_table': 'parcels',
            },
        ),
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areah', models.FloatField(default=0, verbose_name='Area(Ha)')),
                ('perm', models.FloatField(default=0, verbose_name='Perimeter')),
                ('plotno', models.BigIntegerField(unique=True, verbose_name='Plot NO')),
                ('lrnumber', models.CharField(max_length=80, unique=True, verbose_name='LRNumber')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Geometry')),
            ],
            options={
                'verbose_name_plural': 'uploads',
                'db_table': 'uploads',
            },
        ),
        migrations.CreateModel(
            name='ParcelDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_use', models.CharField(choices=[('A', 'Agricultural'), ('R', 'Residential'), ('C', 'Commercial'), ('RC', 'Recreational'), ('T', 'Transport')], default=None, max_length=15, verbose_name='Land_use')),
                ('tenure', models.CharField(choices=[('freehold', 'Freehold'), ('leasehold', 'Leasehold')], default=None, max_length=10, verbose_name='Tenure')),
                ('status', models.CharField(choices=[('on_sale', 'on sale'), ('in_use', 'in use'), ('restricted', 'restricted')], default='in_use', max_length=10, verbose_name='Status')),
                ('improvements', models.CharField(default='nil', max_length=100, verbose_name='Land Improvements')),
                ('encumbrances', models.CharField(default='nil', max_length=100, verbose_name='Encumbrances')),
                ('purchase_date', models.DateTimeField(verbose_name='Purchase Date')),
                ('registered', models.DateTimeField(default=datetime.datetime.now)),
                ('parcel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', related_query_name='details', to='parcels.parcels', verbose_name='Parcels')),
            ],
            options={
                'verbose_name_plural': 'parcel_details',
                'db_table': 'parcel_details',
            },
        ),
    ]
