# Generated by Django 3.2.3 on 2021-06-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=20, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Street'),
        ),
    ]
