# Generated by Django 3.2.3 on 2021-06-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0002_auto_20210614_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='account',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='city',
            field=models.CharField(max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='country_name',
            field=models.CharField(max_length=255, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='ip',
            field=models.CharField(max_length=255, verbose_name='Ip Address'),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='region_code',
            field=models.CharField(max_length=255, verbose_name='Region code'),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='zip_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Zip code'),
        ),
    ]
